### PR TITLE
Fixed error in kubernetes_pod table when using scientific notation for pod resource requests/limits Closes #314

### LINKED ISSUE #314: Error in `kubernetes_pod` table when using scientific notation for pod resource requests/limits
**Describe the bug**

Queries against the `kubernetes_pod` table throw an error if pod requests/limits are expressed in scientific notation.

```
Error: my_kube_cluster: failed to populate column 'containers_resources_limits_std': unknown unit: e6 (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**

Steampipe v2.1.0

**Plugin version (`steampipe plugin list`)**

1.4.0

**To reproduce**
 
1. Configure a k8s cluster connection in your steampipe kubernetes plugin config file.
2. Add a pod to your cluster with requests and limits that use scientific notation. 
```
$ kubectl apply -f <(cat <<END
  apiVersion: v1
  kind: Pod
  metadata:
    name: hello-world-pod
  spec:
    containers:
    - name: hello-world
      image: helm-hello-world:1.0.0
      resources:
        limits:
          cpu: '750e-3'
          memory: '1e9'
        requests:
          cpu: '500e-3'
          memory: '100e6'
  END
  )
```
3. Run a steampipe query for that pod with a `WHERE` clause:  
  `steampipe query 'select * from my_kube_cluster.kubernetes_pod where name like 'hello%'`
4. Observe the error:  
  `Error: my_kube_cluster: failed to populate column 'containers_resources_limits_std': unknown unit: e9 (SQLSTATE HV000)`
5. Clean up.
  `kubectl delete pod hello-world-pod`

**Expected behavior**

I expect the query to run without errors.

**Additional context**

I see a memory unit issue in #284, but this is more of a numeric notation issue.

The kubernetes docs about [Memory Resource Units](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory) contain an example using scientific notation, saying these values are roughly equivalent: `128974848, 129e6, 129M,  128974848000m, 123Mi`

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from kubernetes_pod
+----------------------------------+-------------+--------------------------------------+-----------------+------------------------------------------------------------------->
| name                             | namespace   | uid                                  | selector_search | volumes                                                           >
+----------------------------------+-------------+--------------------------------------+-----------------+------------------------------------------------------------------->
| kube-apiserver-minikube          | kube-system | c902e731-fa72-44af-b565-0965f37c3881 | <null>          | [{"hostPath":{"path":"/etc/ssl/certs","type":"DirectoryOrCreate"},>
|                                  |             |                                      |                 |                                                                   >
|                                  |             |                                      |                 |                                                                   >
| hello-world-pod-1                | default     | 094f579d-3461-4cb1-a56c-98819899f158 | <null>          | [{"name":"kube-api-access-x9v2g","projected":{"defaultMode":420,"s>
| coredns-6f6b679f8f-96jgg         | kube-system | 48a4d4b1-1623-454f-8221-4168409f0d0c | <null>          | [{"configMap":{"defaultMode":420,"items":[{"key":"Corefile","path">
|                                  |             |                                      |                 |                                                                   >
| kube-controller-manager-minikube | kube-system | 8535ce7c-1503-4df6-a51c-55e63f524ae2 | <null>          | [{"hostPath":{"path":"/etc/ssl/certs","type":"DirectoryOrCreate"},>
|                                  |             |                                      |                 |                                                                   >
|                                  |             |                                      |                 |                                                                   >
| kube-scheduler-minikube          | kube-system | 68641490-ae63-4ec7-96e9-016970067933 | <null>          | [{"hostPath":{"path":"/etc/kubernetes/scheduler.conf","type":"File>
| etcd-minikube                    | kube-system | debcc039-0976-4e0f-ba80-472bbb73d759 | <null>          | [{"hostPath":{"path":"/var/lib/minikube/certs/etcd","type":"Dire

> select * from kubernetes_node
+----------+--------------------------------------+---------------+-------------------+-------------+---------------+--------+---------------+--------------+----------------->
| name     | uid                                  | pod_cidr      | pod_cidrs         | provider_id | unschedulable | taints | config_source | capacity_cpu | capacity_memory >
+----------+--------------------------------------+---------------+-------------------+-------------+---------------+--------+---------------+--------------+----------------->
| minikube | 037a100a-45cc-4f9d-89f8-cbddc89de0f0 | 10.244.0.0/24 | ["10.244.0.0/24"] |             | false         | <null> | <null>        | 11           | 8025220Ki       >
|          |                                      |               |                   |             |               |        |               |              |                 >
+----------+--------------------------------------+---------------+-------------------+-------------+---------------+--------+---------------+--------------+---------------
```
</details>

### CODE REVIEW

File: kubernetes/utils.go [hunk 1]
```diff
@@ -1020,16 +1020,36 @@ func normalizeCPUToMilliCores(cpu string) (int64, error) {
...
 			unitPart = memory[i:]
 			break
 		}
+		// Handle the case where 'e' or 'E' is followed by a letter (not +/- or digit)
+		if (r == 'e' || r == 'E') && i+1 < len(memory) {
+			next := memory[i+1]
+			if (next >= 'A' && next <= 'Z') || (next >= 'a' && next <= 'z') {
+				valuePart = memory[:i]
+				unitPart = memory[i:]
+				break
```
Comment (misraved) [inline kubernetes/utils.go:1048]: Do we no longer need the `if r < '0' || r > '9'` check? I do not think it is handled in the code anymore.

File: kubernetes/table_kubernetes_pod.go [hunk 2]
```diff
@@ -618,23 +618,23 @@ func transformPodCpuAndMemoryUnit(ctx context.Context, d *transform.TransformDat
 
 	if param == "limit" {
 		limitCPUMemoryMaps := make([]map[string]interface{}, 0)
-	
-		limitCPUMemoryMap := make(map[string]interface{})
-	
+
 		for _, container := range containers {
+			// Create a new map for each container
+			limitCPUMemoryMap := make(map[string]interface{})
```
Comment (misraved) [inline kubernetes/table_kubernetes_pod.go:624]: @ParthaI, what is the advantage of creating a new map for each container? How does it make the code more effective?

**Review by misraved — COMMENTED** [review]
@ParthaI please take a look at the review comments. Thanks!!

File: kubernetes/utils.go (hunk 1 above)
Comment (ParthaI) [reply kubernetes/utils.go:1048]: Hi @misraved, You're right that the original `r < '0' || r > '9'` check was used to detect the first non-digit character to separate the value and unit.

In the updated logic, that check has been replaced by a more explicit and accurate condition that:

* Identifies the first alphabetic character (excluding `'e'`/`'E'`)
* Handles the special case where `'e'` or `'E'` is followed by another alphabetic character, which isn't valid scientific notation

So functionally, the new implementation **covers and refines** the original intent of the `r < '0' || r > '9'` check. 👍

Let me know if you think we should make that even more explicit!

**Review by misraved — APPROVED** [review]
